# Generated by Django 4.1.1 on 2022-09-18 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_task"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task", old_name="description", new_name="descriptiom",
        ),
    ]
