# Generated by Django 4.1.1 on 2022-09-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_rename_description_task_descriptiom"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task", old_name="descriptiom", new_name="description",
        ),
        migrations.AddField(
            model_name="task", name="done", field=models.BooleanField(default=False),
        ),
    ]
